version: '3.9'

services:
  web:
    build: .
    container_name: taking-note-app
    ports:
      - "5000:5000"
    volumes:
      - .:/app                   # Mount code để sửa trực tiếp khi dev
      - note_data:/app/instance  # Volume lưu database SQLite
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
    restart: always

volumes:
  note_data: